apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.db.name }}-init-job
  namespace: {{ .Values.app }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.db.name }}-init-container
        image: asahran/db_initializer:latest
        command: ["/bin/sh"]
        args: ["-c", "sh ./build-tools/run-migrations.sh"]
      restartPolicy: Never
  backoffLimit: 4
