apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: {{ .Values.app }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - name: {{ .Values.db.name }}-container
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: {{ .Values.db.name }}-config
        - secretRef:
            name: {{ .Values.db.name }}-secret
        ports:
        - containerPort: {{ .Values.db.port }}
        volumeMounts:
        - mountPath: {{ .Values.db.persistentVolumes.readPath }}
          name: {{ .Values.db.persistentVolumes.accessName }}
      volumes:
      - name: {{ .Values.db.persistentVolumes.accessName }}
        persistentVolumeClaim:
          claimName: {{ .Values.db.name }}-pvc
