# Not completed

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.name }}-pv
  namespace: {{ .Values.app }}
spec:
  capacity:
    storage: {{ .Values.db.persistentVolumes.storage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.persistentVolumes.writePath }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.name }}-pvc
  namespace: {{ .Values.app }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistentVolumes.storage }}
