apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-service
  namespace: {{ .Values.app }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
      nodePort: {{ .Values.db.services.nodePort.nodePort }}
  type: NodePort
