apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.name }}-config
  namespace: {{ .Values.app }}
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB: students
  POSTGRES_USER: postgres